### ISSUE TITLE
heroku discussion

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/account#2]
i tried to deploy the app on heroku, but getting some problem ... 
firstly we need some server side on our gatsby app!!
i got this repo :
https://github.com/Muhammadumair0/Gocier-Star-Test

---

but getting issues on how to deploy this app on heroku
i tried to do every thing stated in heroku docs ... It's not working
some issues i got:
1) after updating my gatsby project files, i followed this
https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/
Adding an existing project to GitHub using the command line - User Documentation
Putting your existing work on GitHub can let you share and collaborate in lots of great ways. …
help.github.com
but my github repo is not getting updated, when i do "git status" it shows no modifiction errors!
... well i learned some basic things about gatsby

---

1) heroku with react require using/cloning some packs, that they create. will check them.
2) i think all is fine, you just rushed our development a bit 🙂
3) you must work on my repo - because soon or later i'll extend the team with other developers, so it's necessary to keep a;; stuff in one place.

so 0) please move your code into this repo: https://github.com/GroceriStar/account
and then i'll be able to grab data and check why heroku is not working, ok?

**Comment by atherdon** [comment]
@Muhammadumair0  buzz me when you'll move code int this repo.

ill try deploy on heroku myself and will be able to check logs. i think it'll helps to understand problem more clearly

about serverside data - we have it. will connect that later

**Comment by Muhammadumair0** [comment]
https://github.com/GroceriStar/account

**Comment by Muhammadumair0** [comment]
>package.json
>remove " , "  line 47.

**Comment by atherdon** [comment]
trying it on my heroku account

**Comment by atherdon** [comment]
@Muhammadumair0  let's skip heroku deploy right now. i tried on my account - and deploy are going well, but i have a white page. so maybe more research is required.

let's do other thing, and then i'll try to figure out what is missing. still, i made some updates - so pull data from repo

**Comment by Muhammadumair0** [comment]
ok
