### ISSUE TITLE
heroku deploy

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/account#4]
https://github.com/mickeyreiss/gatsby-on-heroku/blob/master/package.json#L22
https://github.com/gatsbyjs/gatsby/issues/2836
https://www.gatsbyjs.org/docs/deploy-gatsby/#heroku
https://github.com/arielger/gatsby-deploy-heroku/commit/aadcc675bd0e15d3db6d459e43e0833452c1a75a

**Comment by Muhammadumair0** [comment]
much appreciated!

**Comment by atherdon** [comment]
https://groceristar-account-static-gat.herokuapp.com/

```
Failed to load resource: the server responded with a status of 404 (Not Found)
commons.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by Muhammadumair0** [comment]
not working!!
https://gorcier-star-test.herokuapp.com/

**Comment by atherdon** [comment]
@Muhammadumair0 yeah, but build was well. forgt about it right now. i think we'll figure out a better way to preview changes. i just want to have a place - where i can see the progress, without cloning and running code.

**Comment by atherdon** [comment]
we'll not use heroku as our test env
